import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import createIgnore from "ignore";

import { resolvePackagedAppArtifacts } from "../scripts/lib/packaged-app.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("packaged verification authority is the selected app bundle", () => {
  const appPath = path.join(repoRoot, "dist", "Example.app");
  const artifacts = resolvePackagedAppArtifacts(appPath);
  assert.equal(artifacts.appPath, appPath);
  assert.equal(artifacts.asarPath, path.join(appPath, "Contents", "Resources", "app.asar"));
  assert.equal(artifacts.unpackedPath, `${artifacts.asarPath}.unpacked`);
  assert.notEqual(artifacts.asarPath, path.join(repoRoot, ".build", "app.asar"));
  assert.throws(() => resolvePackagedAppArtifacts(path.join(repoRoot, ".build", "app.asar")), /\.app bundle/);
});

test("publication ignore rules retain reconstructed frontend source", async () => {
  const ignoreRules = await readFile(path.join(repoRoot, ".gitignore"), "utf8");
  assert.match(ignoreRules, /^\/recovered\/$/m);
  assert.doesNotMatch(ignoreRules, /^recovered\/$/m);
  const retained = "frontend/src/recovered/ui/sand-form-primitives.css";
  const matcher = createIgnore().add(ignoreRules);
  assert.equal(matcher.ignores(retained), false, `${retained} must remain addable in a fresh repository`);
  assert.equal(matcher.ignores("recovered/generated-output.txt"), true, "root recovery output must remain ignored");
});

test("default packaging keeps the polished checksum-pinned renderer", async () => {
  const source = await readFile(path.join(repoRoot, "scripts", "package-macos.mjs"), "utf8");
  assert.match(source, /import \{ buildFidelityReconstructedAsar \} from "\.\/clean-build\.mjs"/);
  assert.match(source, /await buildFidelityReconstructedAsar\(\)/);
});

test("package dispatcher is target-aware rather than macOS-only", async () => {
  const pkg = JSON.parse(await readFile(path.join(repoRoot, "package.json"), "utf8"));
  assert.match(pkg.scripts.package, /scripts\/package\.mjs/);
  assert.doesNotMatch(pkg.scripts.package, /package-macos\.mjs/);
  const dispatcher = await readFile(path.join(repoRoot, "scripts", "package.mjs"), "utf8");
  assert.match(dispatcher, /detectHostPlatformTarget/);
  assert.match(dispatcher, /package-macos\.mjs/);
  assert.match(dispatcher, /package-linux\.mjs/);
  assert.match(dispatcher, /package-windows\.mjs/);
  assert.match(dispatcher, /package-android\.mjs/);
  const windows = await readFile(path.join(repoRoot, "scripts", "package-windows.mjs"), "utf8");
  const linux = await readFile(path.join(repoRoot, "scripts", "package-linux.mjs"), "utf8");
  const shell = await readFile(path.join(repoRoot, "scripts", "lib", "electron-official-shell.mjs"), "utf8");
  assert.match(windows, /stageOfficialElectronShell/);
  assert.match(linux, /stageOfficialElectronShell/);
  assert.match(windows, /win32/);
  assert.match(linux, /linux/);
  const electronMain = await readFile(path.join(repoRoot, "scripts", "electron-main-production-activation.mjs"), "utf8");
  assert.match(electronMain, /name: "ssh2"/);
  assert.match(electronMain, /name: "asn1"/);
  assert.match(electronMain, /name: "safer-buffer"/);
  assert.match(electronMain, /name: "bcrypt-pbkdf"/);
  assert.match(electronMain, /name: "tweetnacl"/);
  assert.match(electronMain, /external: \["electron", "undici", "ws", "ssh2"/);
  assert.match(electronMain, /externalImports.includes\("ssh2"\)/);
  assert.doesNotMatch(electronMain, /name: "cpu-features"/);
  assert.match(shell, /ELECTRON_SHELL_VERSION = "42\.1\.0"/);
  assert.match(shell, /882047343a9e203c6cfc5d39b166ea9e025dd256943e0d3711f86725ad0e3bd9/);
  assert.match(shell, /0b03582d0a68dce8473fcc090114dabef7eaafd52b6d8cd2c85b000358c6af31/);
  const catalog = JSON.parse(await readFile(path.join(repoRoot, "manifests", "platforms.json"), "utf8"));
  assert.equal(catalog.targets.find((target) => target.id === "linux-x64").status, "implemented");
  assert.equal(catalog.targets.find((target) => target.id === "windows-x64").status, "implemented");
});

test("Router settings use the trusted backend and display recorded inference usage", async () => {
  const store = await readFile(path.join(repoRoot, "source", "shared", "node", "settings", "sand-settings-store.ts"), "utf8");
  const preload = await readFile(path.join(repoRoot, "source", "electron-preload", "preload.ts"), "utf8");
  const mainEdge = await readFile(path.join(repoRoot, "source", "electron-main", "main-edge.ts"), "utf8");
  const inference = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "inference-service.ts"), "utf8");
  const inferenceProduction = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "production.ts"), "utf8");
  assert.match(inferenceProduction, /createBoxWebSearchService/);
  assert.doesNotMatch(inferenceProduction, /createCursorWebSearchService/);
  const cursorSession = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "cursor-session.ts"), "utf8");
  const cursorBackend = await readFile(path.join(repoRoot, "source", "shared", "node", "cursor-backend", "cursor-inference.ts"), "utf8");
  const providers = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "provider-session.ts"), "utf8");
  const codexDirect = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "codex-direct-responses.ts"), "utf8");
  const turnShell = await readFile(path.join(repoRoot, "source", "host", "runner", "turn-run-shell.ts"), "utf8");
  const coordinator = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "inference-router.ts"), "utf8");
  const coordinatorMain = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "main.ts"), "utf8");
  const mcpBridge = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "routed-mcp-bridge.ts"), "utf8");
  const localDocker = await readFile(path.join(repoRoot, "source", "electron-main", "box", "local-docker-host-connector.ts"), "utf8");
  const recoveredRouter = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "settings", "overlay", "router.ts"), "utf8");
  const recoveredView = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "settings", "overlay", "view.tsx"), "utf8");
  const recoveredServer = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "settings", "overlay", "server.tsx"), "utf8");
  const recoveredPanel = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "settings", "overlay", "router-panel.tsx"), "utf8");
  const recoveredPool = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "settings", "overlay", "router-pool.ts"), "utf8");
  const poolSave = await readFile(path.join(repoRoot, "scripts", "lib", "router-pool-save.mjs"), "utf8");
  const localCron = await readFile(path.join(repoRoot, "source", "host", "extensions", "automations", "local-cron-scheduler.ts"), "utf8");
  const automationsExt = await readFile(path.join(repoRoot, "source", "host", "extensions", "automations", "extension.ts"), "utf8");
  assert.match(store, /resolveSandInferenceProvider\(value, s\.inferenceEndpoints\)/);
  assert.match(store, /loaded\.inferenceProvider !== provider\) this\.persist/);
  assert.match(recoveredRouter, /DEFAULT_ROUTER_PROVIDER: RouterProviderId = "openrouter"/);
  assert.match(recoveredRouter, /id: "openrouter",\s*label: "API"/);
  assert.match(recoveredView, /id: "server", label: "Server"/);
  assert.match(recoveredServer, /Token is saved on this computer/);
  assert.match(recoveredServer, /Save proxy/);
  assert.match(recoveredPanel, /title="Keys"/);
  assert.match(recoveredPanel, /title="Assignments"/);
  assert.match(recoveredPool, /export function prepareRouterPoolSave/);
  assert.match(poolSave, /function prepareRouterPoolSave/);
  assert.match(localCron, /isDueLocalCron/);
  assert.match(automationsExt, /LocalCronScheduler/);
  assert.match(automationsExt, /useLocalCronClock/);
  assert.doesNotMatch(automationsExt, /applyOriginalRendererRouterPatch/);
  const desktopBridge = await readFile(path.join(repoRoot, "source", "client-runtime", "desktop-bridge.ts"), "utf8");
  assert.match(preload, /createDesktopBridge/);
  assert.match(preload, /createElectronPreloadTransport/);
  assert.match(desktopBridge, /setInferenceEndpoints: \(document: unknown\) => gatedCall\("inferenceRouter", "setInferenceEndpoints", \{ document \}\)/);
  assert.match(desktopBridge, /getOutboundProxy: \(\) => gatedCall\("remoteBox", "getOutboundProxy"\)/);
  assert.match(desktopBridge, /setOutboundProxy: \(settings: unknown\) => gatedCall\("remoteBox", "setOutboundProxy", settings\)/);
  assert.match(desktopBridge, /getBoxRuntime: \(\) => gatedCall\("localDockerVm", "getBoxRuntime"\)/);
  assert.match(desktopBridge, /setBoxRuntime: \(mode: string\) => gatedCall\("localDockerVm", "setBoxRuntime", \{ mode \}\)/);
  assert.match(mainEdge, /syncHostSettingsToBox\(\{ inferenceProvider: provider \}\)/);
  assert.match(mainEdge, /invoke\(deps\.settingsStore, "setInferenceProvider", provider\)/);
  assert.match(mainEdge, /return \{ provider, usage:/);
  assert.match(mainEdge, /invoke\(deps\.boxRecovery, "restartCoordinator"\)/);
  assert.match(mainEdge, /mode === "local-docker"\) await startLocalDockerBox\(settingsPath\); else await stopLocalDockerBox\(\)/);
  assert.match(mainEdge, /setBoxRuntime", mode === "local-docker" \? "remote" : "local-docker"/);
  assert.match(localDocker, /public\.ecr\.aws\/k0i0n2g5\/cursorenvironments\/universal:sand-box-latest/);
  assert.match(localDocker, /"127\.0\.0\.1:1340:1340"/);
  assert.match(localDocker, /SAND_BOX_AUTO_UPDATE=0/);
  assert.match(localDocker, /dst=\/home\/box\/sand-host\/host-main\.cjs,readonly/);
  assert.match(localDocker, /\.getBoxRuntime\(\) === "local-docker" \? await localConnect\(\) : await remote\.connect\(\)/);
  assert.match(inference, /recordInferenceUsage\(provider/);
  assert.match(inference, /routerSettings\.getInferenceProvider\(\)/);
  assert.match(inference, /typeof extendedUsage\.then === "function"/);
  assert.match(inference, /createProviderPromptSession\(provider, "chat"\)/);
  assert.match(inference, /createProviderPromptSession\(provider, "compact"\)/);
  assert.match(providers, /https:\/\/chatgpt\.com\/backend-api\/codex/);
  assert.match(providers, /headers\.set\("ChatGPT-Account-Id", credentials\.accountId\)/);
  assert.match(providers, /streamCodexDirectResponses/);
  assert.doesNotMatch(providers, /provider\.responses\(configuredCodexModel\(\)\)/);
  assert.match(codexDirect, /store: false/);
  assert.match(codexDirect, /response\.output_text\.delta/);
  assert.match(codexDirect, /type: "function_call_output"/);
  assert.match(providers, /parameters: jsonSchema\(parameters\)/);
  assert.match(providers, /You are Grok Bot, a warm, concise desktop assistant/);
  assert.match(providers, /mcpServers: \{ grok_bot_plugins:/);
  assert.match(providers, /recordRoutedUsage\(provider, usage\)/);
  assert.match(providers, /queryClaude/);
  assert.match(providers, /tools: mcpServerUrl == null \? \[\] : \["mcp__grok_bot_plugins__\*"\]/);
  assert.match(providers, /documentFromPreset\("custom"\)/);
  assert.doesNotMatch(providers, /fetchWithDeadline/);
  assert.doesNotMatch(providers, /openrouter\.ai/);
  assert.match(providers, /effectiveContextWindow\(endpoint\)/);
  assert.match(providers, /maxTokens: contextWindow/);
  assert.match(providers, /OpenRouter needs OPENROUTER_API_KEY/);
  const catalog = await readFile(path.join(repoRoot, "source", "shared", "inference-endpoints.ts"), "utf8");
  assert.match(catalog, /https:\/\/openrouter\.ai\/api\/v1/);
  assert.match(catalog, /gpt-5\.6-sol/);
  const hostRunner = await readFile(path.join(repoRoot, "source", "host", "host-runner-composition.ts"), "utf8");
  assert.match(hostRunner, /agentTokenLimitFromSettings/);
  assert.match(hostRunner, /unusedTokensThresholdToStartBackgroundSummarization: undefined/);
  assert.match(cursorSession, /routedProvider !== "cursor"/);
  assert.match(cursorSession, /hostInferenceCanRunWithoutCursor\(\)/);
  assert.match(cursorSession, /createProviderPromptSession\(provider, sessionOptions\?\.isSummarizationSession === true \? "compact" : "chat"\)/);
  assert.match(cursorBackend, /routedProvider !== "cursor"/);
  assert.match(cursorBackend, /hostInferenceCanRunWithoutCursor\(\)/);
  assert.match(cursorBackend, /createProviderPromptSession\(routedProvider\)/);
  assert.match(poolSave, /apiKeySecret/);
  assert.match(catalog, /gpt-5\.6-sol/);
  assert.match(mainEdge, /resolveSandInferenceProvider\(requested, endpoints\)/);
  assert.match(turnShell, /inferenceProvider === "cursor"/);
  assert.match(turnShell, /createProviderPromptSession\(inferenceProvider, "chat"\)/);
  assert.match(turnShell, /createProviderPromptSession\(inferenceProvider, "compact"\)/);
  assert.match(coordinator, /method !== "sendPrompt" \|\| provider === "cursor"/);
  assert.match(coordinator, /executeTool: async \(definition, toolArgs, toolCallId\)/);
  assert.match(coordinatorMain, /command\(commands, "listRoutedMcpTools", args\)/);
  assert.match(coordinator, /inference-router-transcript\.json/);
  assert.match(mcpBridge, /openWorldHint: !readOnly/);
  assert.match(coordinator, /schemaVersion: 2/);
  assert.match(coordinator, /\["getAgentTranscriptTail", "openAgentTail", "getAgentTranscriptWindow"\]/);
  assert.match(coordinator, /\.map\(projectInferenceRouterTranscriptEntry\)/);
  assert.match(coordinator, /readonly richText\?: string/);
  assert.match(coordinator, /richText: entry\.richText/);
  assert.match(coordinator, /setTimeout\(resolve, 1_200\)/);
  assert.match(coordinator, /method === "reactToMessage"/);
  assert.match(coordinator, /reaction\.by === "me"/);
  assert.match(coordinator, /currentActivity: \{ kind: "thinking" \}/);
  assert.match(coordinator, /onTextDelta/);
  assert.match(coordinator, /streaming/);
  assert.match(coordinator, /postEvent\("agents"/);
  assert.match(coordinator, /createRoutedMcpBridge/);
  assert.match(coordinator, /listRoutedMcpTools/);
  assert.match(coordinator, /executeRoutedMcpTool/);
  assert.match(mcpBridge, /server\.listen\(0, "127\.0\.0\.1"/);
  assert.match(mcpBridge, /readOnlyHint: readOnly/);
  assert.match(mcpBridge, /request\.url !== `\/mcp\/\$\{secret\}`/);
  assert.match(coordinator, /kind: "send-message"/);
  assert.match(coordinatorMain, /createCoordinatorInferenceRouter/);
  assert.match(coordinatorMain, /routed\.handled/);
});
